Feature/hero.html
DariusBlac/project-clock-shop pull request #1
Opened 2023-05-04 17:42 UTC by AndreyPysarenko

2023-05-04 17:44 UTC, AndreyPysarenko commented
button для наглядності, потім перероблю в div коли буде спрайт svg

2023-05-04 20:42 UTC, DariusBlac requested changes

2023-05-04 20:42 UTC, DariusBlac commented on src/partials/hero.html
> +      <img
Тег імг має лежати в тегу пікчер

2023-05-04 20:42 UTC, DariusBlac commented on src/partials/hero.html
> +          </picture>
тег імг має лежати в тегу пікчер

2023-05-05 06:12 UTC, AndreyPysarenko commented on src/partials/hero.html
> +      <img
виправлено

2023-05-05 06:12 UTC, AndreyPysarenko commented on src/partials/hero.html
> +          </picture>
виправлено

2023-05-05 07:06 UTC, DariusBlac approved these changes

2023-05-05 07:06 UTC, merged