Feature/catalog
DariusBlac/project-clock-shop pull request #3
Opened 2023-05-05 08:52 UTC by Annacheer

2023-05-05 09:27 UTC, DariusBlac requested changes

2023-05-05 09:27 UTC, DariusBlac commented on src/css/catalog.css
> +}
все що вище потрібно видалити воно буде зпідтягуватися з інших файлів

2023-05-05 09:27 UTC, DariusBlac commented on src/partials/catalog.html
> +    <main>
все що вище видалити залишаєш лише section

2023-05-05 20:30 UTC, Annacheer commented on src/css/catalog.css
> +}
Видалила

2023-05-05 20:32 UTC, Annacheer commented on src/partials/catalog.html
> +    <main>
Видалила

2023-05-06 08:59 UTC, DariusBlac approved these changes

2023-05-06 08:59 UTC, merged